version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
    command: npm start
